title : Arya Gadage
description : About Me - I am a pre doctoral fellow at Columbia University in the Department of Economics and Program for Economic Research (PER). I am working with Prof Micheal Best and Prof Haoge Chang.
theme : minima

#Add Navigation Links

header_pages:
- index.md
- about.md
